export const LOAD_DATA_INITIATION = 'JOB_POSTINGS/LOAD_DATA_INITIATION';
export const LOAD_DATA_SUCCESS = 'JOB_POSTINGS/LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'JOB_POSTINGS/LOAD_DATA_FAILURE';
