export const LOAD_DATA_INITIATION = 'ANNOUNCEMENTS/LOAD_DATA_INITIATION';
export const LOAD_DATA_SUCCESS = 'ANNOUNCEMENTS/LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'ANNOUNCEMENTS/LOAD_DATA_FAILURE';
