export const LOAD_DATA_INITIATION = 'APPROVEUSER/LOAD_DATA_INITIATION';
export const LOAD_DATA_SUCCESS = 'APPROVEUSER/LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'APPROVEUSER/LOAD_DATA_FAILURE';
