export const LOAD_DATA_INITIATION = 'NEWSLETTER/LOAD_DATA_INITIATION';
export const LOAD_DATA_SUCCESS = 'NEWSLETTER/LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'NEWSLETTER/LOAD_DATA_FAILURE';
